### ISSUE TITLE
Should this mirror / host envisioning.io? 

### ISSUE THREAD

**Issue by RichardLitt** [envisioning/envisioning.github.io#1]
Saw some bugs on envisioning.io, and I was hoping to fix them, but it doesn't look like the code is hosted here. 

Should envisioning.github.io basically be an open source version of envisioning.io, perhaps?

**Comment by michellzappa** [comment]
Complete site overhaul taking place soon.
Documentation here:
https://docs.google.com/document/d/1eP3XanbuhNPmp3gVvjU5D_YOmNRS-qmaADafNgpj5CY/edit#heading=h.namtxaljfia8

New site will definitely live on Github. Let's discuss.

**Comment by RichardLitt** [comment]
Sounds good.
