### ISSUE TITLE
Troca de #permalink ao navegar o site

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#10]
http://envisioning.io/#futurekit, etc.

**Comment by fabiokandrade** [comment]
para isso vou usar o **hash**, pode ser?
Ficará assim:
- www.dominio.com.br/#disrupting
- www.dominio.com.br/#futuredeck
- www.dominio.com.br/#readiness
etc...

Não sei se vai funcionar em browsers antigos, acho que não. Tem que testar em explorer, pelo que eu li no 10+ funciona.

Para isso vou usar
```
window.location.hash
window.location.href = "...#projeto"
```

**Comment by michellzappa** [comment]
Perfeito. É isso aí :-)
