### ISSUE TITLE
Tipo de núcleo "meta"

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#11]
Teremos 2 ou mais Núcleos que não aparecem no mapa da home. Isso se faz direto no banco de dados, ou precisa de código para a exceção?

![screenshot 2015-03-03 15 19 47](https://cloud.githubusercontent.com/assets/5923523/6469131/bc4323cc-c1b8-11e4-9255-895d20d04046.png)

**Comment by fabiokandrade** [comment]
não entendi :confused:

**Comment by michellzappa** [comment]
Me expliquei mal.
Quis dizer que existem dois tipos de página: os núcleos coloridos (que
aparecem na home) e os núcleos próprios da Envisioning (que tem ícone
cinza, e só aparecem quando você clica em alguma página relacionada).
Faz sentido?

**Comment by fabiokandrade** [comment]
incluir como **project** e linkar
