### ISSUE TITLE
Integração com banco de dados

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#12]
Podemos tentar simplificar isso? Não vejo **tanta** necessidade de integrar com Google Docs, se um JSON resolver.

**Comment by fabiokandrade** [comment]
já achei uma forma boa de  integrar com Google Docs, vai ser até mais fácil pra mim. Consigo pegar o conteúdo da planilha em Json e tratar. Vou fazer isso semana que vem

**Comment by fabiokandrade** [comment]
estou acabando esta parte. Tudo bem para vc se eu fizer uma planilha do "zero" e vc preencher? Vai ser mais rápido que adaptar sua planilha.

**Comment by michellzappa** [comment]
Perfeitamente.
