### ISSUE TITLE
Criar modelo de Div para inserção de conteúdo sobre núcleo

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#15]
- Título
- Slogan
- Conteúdo
- Permalink

![screenshot 2015-03-03 15 23 56](https://cloud.githubusercontent.com/assets/5923523/6469242/6f715cd4-c1b9-11e4-9dad-bdcd5c70b217.png)

![screenshot 2015-03-03 15 24 47](https://cloud.githubusercontent.com/assets/5923523/6469243/70e817c4-c1b9-11e4-8e8f-61d3170b2cda.png)

**Comment by fabiokandrade** [comment]
já criei a DIV, mas preciso deste css. não sei como fazer.

**Comment by michellzappa** [comment]
Quis dizer a configuração do DIV padrão, em qual aparece o título, slogan e
texto descrevendo cada núcleo. Você meio que já tem isso feito.

**Comment by michellzappa** [comment]
<div class="node">
<h1>Title</h1>
<h2>Slogan</h2>
<p>Descrição</p>
<div class="link"> 
<a href="Permalink">Permatext</a>
</div>

Com isso no output, eu faço o CSS ;-)

**Comment by fabiokandrade** [comment]
feito. Pode incluir como HTML na própria coluna texto.
