### ISSUE TITLE
Título do núcleo/pessoa/projeto em .circlecenter

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#17]

**Comment by fabiokandrade** [comment]
**DESIGN:** o campo texto aceita qualquer coisa de html: (img, div, etc...). Neste caso, vc mesmo pode incluir o que e como quiser, basta inserir o html e montar o css.

**Comment by michellzappa** [comment]
Perfeito!

**Comment by michellzappa** [comment]
Só me ajuda a entender como inserir os diferentes campos do JSON (label,
text, permalink) no JS?
Eu vejo onde em mapa.js o campo 'text' é inserido, mas não quero quebrar o
resto.

**Comment by fabiokandrade** [comment]
não precisa mexer no mapa.js não. mexe direto na coluna TEXT da tabela. Olha a linha FYFS, por exemplo: coloquei um negrito

**Comment by michellzappa** [comment]
Entendi isso.
Mas seria sensato usar o título e permalink como elementos separados da
caixa de texto.
Não faz sentido jogar três tipo de conteúdo diferentes na mesma caixa.

**Comment by fabiokandrade** [comment]
eu poderia até automatizar isso, mas vai ficar mais difícil e restrito o layout do conteúdo do .circlecenter
Seria melhor vc colocar por enquanto, pelo menos até fechar o layout, depois automatizo o link.

**Comment by fabiokandrade** [comment]
qdo acabar esse layout me avisa pra eu automatizar.

**Comment by michellzappa** [comment]
http://envisioning.github.io/mapa.html#Futurekit
Só precisa posicionar <h2> e o botão.

**Comment by fabiokandrade** [comment]
ok, me avisa qdo posicionar.

**Comment by michellzappa** [comment]
Pode inserir o título como <h2> e permalink como <div>. Eu faço alterações
na posição se for preciso. :)
