### ISSUE TITLE
Link de volta para Home nem sempre funciona.

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#21]
Também deve eliminar o #hash da URL quando você volta.

**Comment by fabiokandrade** [comment]
Testei em tudo e sempre voltou. Talvez tivesse alguma relação com outro bug que já foi resolvido. Teste, por favor, e me indique em qual status dá o erro se acontecer.

Qto a eliminar o hash, vou ter que deixar um hash 'vazio' no final, senão o browser dá um refresh.
(feito, sobe no próximo git push)

**Comment by michellzappa** [comment]
Show. Obrigado!
