### ISSUE TITLE
Algumas páginas não geram linhas conectoras entre núcleos

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#22]
![screenshot 2015-03-31 14 49 02](https://cloud.githubusercontent.com/assets/5923523/6925330/1c9b47a6-d7b5-11e4-855a-89e97b154a69.png)

**Comment by fabiokandrade** [comment]
esse erro é por conta de espaço a mais entre as vírgulas do link. Vou fazer um trim automático
