### ISSUE TITLE
Sugestão de como distribuir núcleos por tipo

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#23]
Exemplo: Página com 1/2/5 nodes associados.

![img_20150331_145406417_hdr](https://cloud.githubusercontent.com/assets/5923523/6925494/fda84cda-d7b5-11e4-85c1-33bd8bc4138a.jpg)

**Comment by fabiokandrade** [comment]
fiz um teste no último commit. 42e5962bc0296662bf6460f4da3748a19688efc2
dá uma olhada.
abs

**Comment by michellzappa** [comment]
MUITO melhor! Está 95% perfeito.

Se tiver um elemento, ele deveria ficar exatamente em 90º, 180º ou 270º.

Faz sentido? Posso ilustrar com screenshot também.

**Comment by fabiokandrade** [comment]
posso fazer isso, mas só qdo tem um elemento? Achei que ficou muito 'reto' parecendo uma cruz.
o posicionamento não tão alinhado me pareceu mais orgânico. Mas deixo reto se vc prefere.

**Comment by michellzappa** [comment]
concordo que a condição de 1 só elemento pode ficar estranho.
vou evitar isso na manipulação da planilha.
se puder colocar dessa maneira de cruz, agradeço.

**Comment by fabiokandrade** [comment]
mexi nessa distribuição. Esse algoritimo é bem complexo, pois não sabemos de que lado vai haver overlapping. Da forma como está acho que é o melhor que consigo fazer por hora. Se o número de elementos mudar muito, pode haver muito overlapping e comportamentos inesperados.

**Comment by michellzappa** [comment]
MUITO melhor. Valeu.
