### ISSUE TITLE
Aumentar tamanho de ícone aberto para 150 x 150 px

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#25]
![screenshot-2015-03-31-16 46 26](https://cloud.githubusercontent.com/assets/5923523/6927758/c843de96-d7c5-11e4-9536-cc6317932d94.jpg)

**Comment by michellzappa** [comment]
Para indicar hierarquia.

**Comment by fabiokandrade** [comment]
feito.
Fiz mudando a escala, o que significa que pode haver uma pequena variação (de 1 ou 2 pixels) dependendo do ícone. Mudando a escala muda todo o ícone proporcionalmente, inclusive a borda.

**Comment by michellzappa** [comment]
Muito obrigado.
