### ISSUE TITLE
<circle ID="[id]" class........>

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#30]
Colocar ID do JSON como ID do círculo para eu poder criar regras de CSS.

**Comment by fabiokandrade** [comment]
você diz do círculo central? Neste caso melhor colocar uma classe, pois já uso o id do 'json' em outro lugar e pode dar conflito. Pode ser?
Você vai usar uma regra de css para cada id? e quando entrar outro id terá que alterar o css? vamos trocar uma ideia sobre isso, talvez eu possa pensar numa solução melhor.

**Comment by michellzappa** [comment]
Pode ser classe sim.
Qualquer coisa para identificar o círculo em CSS (para eu poder trocar
cores de H2, botão, etc)
