### ISSUE TITLE
Novo tipo de núcleo: "tool"

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#34]
Vou precisar de um tipo de núcleo exclusivo para as ferramentas da Envisioning, tipo banco de dados, conselheiros, tecnologia de site, etc.

Estão indicados como "tool" na coluna "type" da DB.
Eles obedecem o mesmo layout que "type:node", mas como nunca tem "type:project" associado, podem ser exibidos da mesma forma que "Advisors" está agora. 

Se você puder agrupar todos "type:tool" do lado esquerdo, junto aos núcleos, fica perfeito.

Muito obrigado!

**Comment by fabiokandrade** [comment]
dá pra fazer, mas vai demorar um pouco pois preciso reescrever toda a lógica dos types.

enquanto não fizer, o que estiver linkado a um elemento do tipo tool ficará fora de órbita e eventualmente provicará erros.
![screen shot 2015-04-10 at 1 10 03 pm](https://cloud.githubusercontent.com/assets/10994063/7091787/04a12cda-df83-11e4-9850-e66c5fa7b252.png)

**Comment by michellzappa** [comment]
(esperar)
