### ISSUE TITLE
Link "Return Home" junto ao ícone

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#35]
Não me acertei com o HTML+JS ainda, sorry!

![screenshot 2015-04-10 16 47 59](https://cloud.githubusercontent.com/assets/5923523/7091445/93750efe-dfa1-11e4-8a95-103785a88f0c.png)

**Comment by fabiokandrade** [comment]
esse 'Return Home' é uma imagem ou texto?
