### ISSUE TITLE
Experimentar com labels nos nodes durante Mouseover

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#38]

**Comment by michellzappa** [comment]
Tenho uma solução talvez relativamente simples.

On mouseover:
- Deixar imagem 50% branca (tipo com um span semitransparente)
- Inserir [span] com título do node selecionado
- (Opcional) Aumentar 20% tamanho do círculo

Eu faço todo CSS. Se você conseguir injetar dois span on mouseover, eu resolvo o resto.

Valeu!

Tipo assim:
![screenshot 2015-04-15 20 20 36](https://cloud.githubusercontent.com/assets/5923523/7167444/e61e9526-e3ac-11e4-8f75-70b53b753f6d.png)

**Comment by fabiokandrade** [comment]
implementado.
pode usar o css de .labelDiv  e .labelDiv p para configurar.
Parece que existe uma forma de centralizar verticalmente o texto numa DIV usando display table, mas não sei bem como funciona.
