### ISSUE TITLE
Feature: View all [People / Nodes / Projects]

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#39]
Tipo assim, ou mais simples:

![screenshot 2015-04-11 23 20 42](https://cloud.githubusercontent.com/assets/5923523/7103497/65a56c8e-e0a1-11e4-8582-68435e4da107.png)

**Comment by fabiokandrade** [comment]
feito em 80d370ae09df6c2596b77787ca55026eeef7089d
ainda sem "intercalar"
preciso falar com vc sobre essa intercalação: não vai caber.

**Comment by michellzappa** [comment]
Obrigado!!!
Intercalar foi só uma sugestão estética. Zero prioridade. Podemos
considerar pronto.

**Comment by fabiokandrade** [comment]
blz!
não me preocupei com o design.
vc pode colocar na tag e posição que quiser, só manter a classe e o data-type.

(Enviado via celular)

**Comment by michellzappa** [comment]
Yes, comecei e mexer mas tive que parar na metade. Deixa comigo.
