### ISSUE TITLE
Pessoa.svg

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#41]
Carregar pessoa.svg parece demorar muito, comparado com o resto da página.
Existe alguma forma alternativa de carregar os JPEGs? :-)

**Comment by fabiokandrade** [comment]
não tem como mudar isso. é uma lógica bem complicada para incluir os JPEGs dentro do SVG.
Não me pareceu lento considerando o tempo total de carregamento e considerando que tudo é carregado em background (sem interromper o fluxo de navegação). Você está percebendo uma lentidão? Onde exatamente?

**Comment by michellzappa** [comment]
Talvez tenha a ver com o acesso dos JPEGs em si -- mas carregar os ícones das pessoas costuma demorar mais do que o resto da página toda. Só queria saber & entender ;-)

**Comment by fabiokandrade** [comment]
pode ser lentidão do Github sim, poderíamos colocar os JPEGs em algum servidor mais rápido, tipo amazon S3 ou algum CDN. Se quiser fazer isso é possível, mas vc teria que configurar o CORS (Cross-origin resource sharing)

**Comment by michellzappa** [comment]
Perfeito. Fica pro 2.0.
