### ISSUE TITLE
Esconder nodes não visualizados em página de núcelo

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#5]
![screenshot 2015-03-03 15 13 25](https://cloud.githubusercontent.com/assets/5923523/6468994/d8ad48f4-c1b7-11e4-8865-40059ebbe60a.png)

**Comment by fabiokandrade** [comment]
escondendo as labels c775ca0  isso já ficou resolvido, certo?

**Comment by fabiokandrade** [comment]
resolvido.
