### ISSUE TITLE
Esconder títulos de núcleos

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#7]
![screenshot 2015-03-03 15 15 09](https://cloud.githubusercontent.com/assets/5923523/6469036/1659e5b8-c1b8-11e4-99ee-6fc704df83e4.png)

**Comment by fabiokandrade** [comment]
não é mais para ter os títulos? nunca? ou em algum momento eles tem que aparecer?

**Comment by michellzappa** [comment]
Acho que não precisa de títulos na visualização dos ícones. Só aparecem
quando clicados (página aberta).
