### ISSUE TITLE
Organizar núcleos relacionados em ordem circular

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#8]
01–05h: Pessoas
05–07h: Projetos
07–11h: Núcleos

![screenshot 2015-03-03 15 16 13](https://cloud.githubusercontent.com/assets/5923523/6469064/3e2641fe-c1b8-11e4-8dd5-8e7616fbe079.png)

**Comment by fabiokandrade** [comment]
precisa testar com elementos reais. E se forem muitos elementos e uma banda sobrescrever a outra?

**Comment by michellzappa** [comment]
Vamos testar com conteúdo real logo menos.

**Comment by fabiokandrade** [comment]
vide #23
