### ISSUE TITLE
Inserir link de volta para home

### ISSUE THREAD

**Issue by michellzappa** [envisioning/envisioning.github.io#9]
![screenshot 2015-03-03 15 17 42](https://cloud.githubusercontent.com/assets/5923523/6469085/759455fe-c1b8-11e4-8353-5aa4db436804.png)

**Comment by fabiokandrade** [comment]
fica sempre que não for a home, certo? vc pode commitar esse svg? não achei...

**Comment by michellzappa** [comment]
Exato. Está em:

/assets/nodes/envisioning.svg

**Comment by fabiokandrade** [comment]
feito. 6038a7cd9d3b735dd24bfadb7ec0a41bbaa72b26
